-- AlterTable
ALTER TABLE "Teacher" ALTER COLUMN "estimatedSalary" SET DEFAULT 0,
ALTER COLUMN "estimatedSalary" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "percent" SET DEFAULT 40,
ALTER COLUMN "percent" SET DATA TYPE DOUBLE PRECISION;
